require('dotenv').config();
const express = require('express');
const path = require('path');
const pairing = require('./routes/pairing');
const qr = require('./routes/qr');
const { initWA } = require('./utils/whatsapp');
const app = express();
initWA();
app.use(express.json());
app.use('/', express.static(path.join(__dirname, '../frontend/index.html')));
app.use('/api/pair', pairing);
app.use('/api/qr', qr);
const PORT = process.env.PORT||3000;
app.listen(PORT, ()=> console.log(`Server on ${PORT}`));
